version: "3"

services:
  server:
    container_name: repoInfo4Bots
    build: .
    command: yarn dev
    ports:
      - "7023:7023"
      - "9229:9229"
    volumes:
      - .:/usr/repoInfo4Bots
    environment:
      NODE_ENV: development